### ISSUE TITLE
Sample Mean Function Done

### ISSUE THREAD

**Issue by ryanplumer** [mbarton40/FireDucks-MATH408#2]
Hi @jlivsey 

We have finished up a function in which we can pick a mean and then have the function return the closest 5, 10, 15, or however many we choose. We're now going to try an ANOVA test on these sample means and possibly look into DTW packages over our spring break. Is this the general direction you were thinking for us to head in?

Our goal for the final function as of right now is to input a mean, and to output plots of significant (from ANOVA test) time series plots.

Do you have any guidance, suggestions, issues, or anything that you'd like to share?

Thanks!
Fire Ducks

**Comment by jlivsey** [comment]
This all sounds great! 

Can you provide a minimal working example so I can understand the functionality of what you wrote?

**Comment by mbarton40** [comment]
@jlivsey 

Hi Dr. Livsey. I just pushed what I had locally on my laptop. Also here is a typical run-through of what our code is doing in the `TS_SampleMeansAndANOVA.R` File:


 Basically in this file, it is reading in all of the data in the beginning and then taking a random sample from the observations (default is 10). It then pulls all of those samples from our unadjusted time series data frame and assigns it to `sampleMean_Unadj_DF`. It does some rearranging and then calculates the sample mean for each time series and then takes the absolute difference of that mean from an input mean (In our case, you can `our_mean_cluster(30000)` it would be taking the absolute difference of sample means from 30000. Then it sorts them by abs difference and takes the first however many series you want to test (default is 5). Then, it runs a one-way ANOVA test on this data and prints what time series were tested and the probability for the F distribution corresponding to the test. We are still working on seeing if useful data can come from this (maybe multiple trials) and working on the plotting idea.

```
source("TS_FullSource.R")

#Gets the function ready to run samples.
set.seed(3322)
intToSample <- 2:325

#A function that takes a mean, sample size, and the number of series you want,
#produces a random sample and takes the mean for each time series and abs diff
#from the given mean.
our_mean_cluster <- function(m, numOfSamples = 10, numSeries = 5){
  #Takes the input for number of samples and finds the index of those in
  #relation to the dates
  colIndexSample <- sample(intToSample, numOfSamples)
  colIndexSampleSorted <- sort(colIndexSample)
  
  #Takes a random sample from the data frame containing all TS
  sampleMean_Unadj_DF <- All_Unadj_DF[,1] %>%
    cbind(All_Unadj_DF[,colIndexSampleSorted]) %>%
    rename("TS_Names" = ".") %>%
    mutate(TS_Sample_Means = rowMeans(sampleMean_Unadj_DF[,2:(numOfSamples+1)]))
  
  #Takes the absolute difference between input mean and sample mean and
  #adds a column containing that to the df
  orderedMeans <- sampleMean_Unadj_DF %>%
    mutate(AbsDiff = abs(TS_Sample_Means - m)) %>%
    arrange(AbsDiff)
  
  
  PCTS <- (orderedMeans[1:numSeries,])
  PCTS_T <- as.data.frame(t(PCTS))
  names_compared <- PCTS_T[1,]
  print(names_compared)
  colnames(PCTS_T) <- PCTS_T[1,]
  PCTS_T <- PCTS_T[-1,]
  
  pre_ANOVA_PCTS <- gather(PCTS_T, "TS_Names", "Value")
  
  #ANOVA Test (1-way)
  PCTS_SampleMeanANOVA = aov(Value ~ TS_Names, data = pre_ANOVA_PCTS)
  print(summary(PCTS_SampleMeanANOVA))
  #Pass/Fail List of TS that are either good with H0 or H1
  #Plot the list if it passes, if not return NOTHING
  
}

our_mean_cluster(30000)
```


Also, the DTW is coming along smooth as well and can be found in `TS_DTW.R`. This file basically sets our `All_Unadj_DF` data frame up for a distance by DTW function and then creates a hierarchical clustering of that distance by average difference and then creates a dendrogram to quickly capture that data. Another question I have is what is the best way to look at this dendrogram and pull good information from it. It looks accurate and possibly more helpful than sample means/ANOVA but how can be take this data into account and pull out time series that are good to cluster? What's a good threshold? Are there better commands to see all of the dendrogram/labels?

Thank you
-Matt

**Comment by mbarton40** [comment]
Just a quick comment...I had to fix some things and add a few parts in the script so it does look different than above. Also worked on creating a plot from the ones that are potentially "clusterable"
-Matt

**Comment by mbarton40** [comment]
@jlivsey 
Just wanted to follow up on the questions and examples I posted for our function and the DTW work. 

Hope to hear from you soon and thank you,

Matt

**Comment by jlivsey** [comment]
Apologies about the delay. I tried to run this last week but got the following error

```r
Error: Problem with `mutate()` column `TS_Sample_Means`.
ℹ `TS_Sample_Means = rowMeans(sampleMean_Unadj_DF[, 2:(numOfSamples + 1)])`.
x object 'sampleMean_Unadj_DF' not found
```

I meant to dig deeper but it looks like it is more extensive and we should setup a video call to discuss.
