### ISSUE TITLE
Draft Report Completed

### ISSUE THREAD

**Issue by mbarton40** [mbarton40/FireDucks-MATH408#3]
@jlivsey 
We finished our first draft of our write up! Kampbell shared this with you via Overleaf and we would love your take on it when you have the time!

- FireDucks

**Comment by jlivsey** [comment]
Reading now... stay tuned....

**Comment by jlivsey** [comment]
I marked up the PDF file and uploaded it to the Overleaf repo. I think you should add a Section on technical details. Show some formulas and algorithms for how DTW works. Overall, great work.

**Comment by mbarton40** [comment]
Hi @jlivsey !

We reworked our draft between the comments from you and Dr. Cheng! The Overleaf should have the most up-to-date version!

We also have a completed poster for you to look at which is in the "PIC Math - FireDucks" Google Drive shared with you. If you have a chance, we would love to hear your feedback for that as well.

Thanks!
FireDucks
